Developmment
hunter4466/International_food_conference pull request #2
Opened 2021-07-01 21:24 UTC by hunter4466

Created about.html and index html
Added styles on about.css and index.css
Added functionality with about.js, index.js, and menu.js with javascript.
Fixed linters errors.
Finished project.

2021-07-01 21:30 UTC, henatan99 requested changes
# Status: Invalid :warning: 

You have a failing linters check. Please make sure all GitHub linter checks have passed before requesting code review.

2021-07-01 22:40 UTC, Davidosky007 requested changes
Hi @hunter4466, 

Good job so far going beyond the required requirements 💪 !
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
* Please fix the overflowing images and contents causing your page to overflow check comments below for hints on how to fix it
* Pull request should have a descriptive title please add one 🙏 
* The link to your Video presentation is missing, please attach it to your PR 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-01 22:40 UTC, Davidosky007 commented on index.html
> +        <h1 class="sec_1_greetings">"Hello! Chefs community"</h1>
* This line of text (hello chefs community) is not  visible, please  adjust it 🙏 
![Screenshot (123)](https://user-images.githubusercontent.com/52497246/124194328-4ae48b80-dac0-11eb-8510-680a93f934e8.png)

2021-07-01 22:40 UTC, Davidosky007 commented on index.html
> +                <p class="pr_box_parraph">Listen to chefs around the world about their techniques and the way they walkthrough kitchen issues.</p>
* These are articles and should be wrapped in `article` tags, please make the correction in other places it reoccurs

2021-07-01 22:40 UTC, Davidosky007 commented on Assets/Styles/index.css
> +  top: 0.001vw;
* I suggest you use VW unit carefully as it takes the whole available width of your viewport you should subtract padding and margins before using this unit . This is making your page overflow kindly adjust the viewport unit.
* ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
![Screenshot (125)](https://user-images.githubusercontent.com/52497246/124195943-4b325600-dac3-11eb-917b-b6b30e00c99d.png)

2021-07-02 00:59 UTC, Davidosky007 commented on index.html
> +        <h1 class="sec_1_greetings">"Hello! Chefs community"</h1>
* Good job making the requested changes but i can see your middle section on mobile view has some issues 
* YOURS:
![Screenshot (127)](https://user-images.githubusercontent.com/52497246/124205244-c2261980-dad8-11eb-828e-15d9a89e83d8.png)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ORIGINAL :
![Screenshot (128)](https://user-images.githubusercontent.com/52497246/124205291-df5ae800-dad8-11eb-85d6-62cc0b80cbc9.png)

2021-07-02 00:59 UTC, Davidosky007 commented on Assets/Styles/index.css
> +  top: 0.001vw;
* Well done fixing this 👍

2021-07-02 01:01 UTC, Davidosky007 requested changes
Hi @hunter4466, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
* Please fix this one issue and submit it for review, you almost done 👍 
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-02 01:40 UTC, vichuge approved these changes
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-02 02:21 UTC, merged